IgaKongressBundle:
    resource: "@IgaKongressBundle/Controller/"
    type:     annotation
    prefix:   /
IgaKongressBundle:
    resource: "@NavisUserBundle/Controller/"
    type:     annotation
    prefix:   /
_security_check:
     pattern:  /login_check

_security_logout:
     pattern:  /logout

