<?php

namespace Navis\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FacebookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FacebookRepository extends EntityRepository
{
}